version: '3.9'

services:
  hawkeapp:
    container_name: hawkeapp
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./hawkeapp:/hawkeapp
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psdb
  psdb:
    container_name: psdb
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword